name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CLIENT_ID_PAYPAL=$CLIENT_ID_PAYPAL CLIENT_ID_GOOGLE_MAPS=$CLIENT_ID_GOOGLE_MAPS CLIENT_ID_POSITIONSTACK=$CLIENT_ID_POSITIONSTACK npm run build
        env:
            CLIENT_ID_PAYPAL: ${{secrets.CLIENT_ID_PAYPAL }}
            CLIENT_ID_GOOGLE_MAPS: ${{ secrets.CLIENT_ID_GOOGLE_MAPS }}
            CLIENT_ID_POSITIONSTACK: ${{ secrets.CLIENT_ID_POSITIONSTACK }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}